### ISSUE TITLE
about shaderMaterial invalid.

### ISSUE THREAD

**Issue by baiej214** [petrbroz/forge-viewer-utils#1]
@petrbroz 
你好，Petr Broz
我在stackoverflow看到了一些你回答问题的文章，所以才找到你。
我最近在处理forge中使用shaderMaterial的事情，但是我发现forge从v7.3以后，不能正常使用frags.setMaterial(fragId, shaderMaterial)这样的方法来修改material，而且到目前为止都没有找到可行的方法，所以想向你咨询这个问题，你是否了解相关情况，或者有解决的办法？
这是一个例子：https://codepen.io/petrbroz/pen/gObBwRj?editors=1111
你可以在settings->js中修改forge的版本，来验证这个问题。
期待你的回复，十分感谢！

**Comment by petrbroz** [comment]
Hi! This is because somewhere around the version 7.3 the viewer team switched over to WebGL2, and with that change, custom materials need a little bit of extra setup to work correctly. I've documented the process in https://forge.autodesk.com/blog/custom-shader-materials-forge-viewer.

**Comment by baiej214** [comment]
谢谢你的帮助，问题解决了。 十分感谢！

**Comment by petrbroz** [comment]
总是很乐意提供帮助 :)
